### ISSUE TITLE
Adding data table component.

### ISSUE THREAD

**Issue by ABB65** [TurkeyLearningInitiative/frontend#12]
## Summary
Adding and configuring data table component for admin pages.
It needs to have support for listing, search, filtering, and singular/multiple operations.
(React-table etc.)

## Checklist
- [x] I joined a screenshot of the app before and after the fix.
[upload the screenshot here]

**Comment by kivircik-parantez** [comment]
<img width="1609" alt="image" src="https://user-images.githubusercontent.com/54854223/219446524-03b1cfc6-feb1-4aca-8c48-391818abb548.png">
